# Generated by Django 3.1.2 on 2023-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surepass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarapi',
            name='aadhaar_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
